class MuezzinData {
  static final List<Map<String, dynamic>> muezzinData = [
    {
      "category": "مؤذني الحرم المكي ومكة",
      "muezzins": [
        {"name": "حمد بن أحمد الدغريري", "id": "daghriri"},
        {"name": "أحمد عبد الله بصنوي", "id": "basanawi"},
        {"name": "محمد علي شاكر", "id": "shaker"},
        {"name": "توفيق خوج", "id": "khoj"},
        {"name": "نايف فيده", "id": "fida"},
        {"name": "أحمد نحاس", "id": "nahhas"},
        {"name": "ماجد العباس", "id": "abbas"},
        {"name": "أحمد يونس خوجه", "id": "khoja"},
        {"name": "سامي عبدالرحيم ريس", "id": "rayes"},
        {"name": "عماد بقري", "id": "baqri"},
        {"name": "سعيد عمر فلاته", "id": "fallatah"},
        {"name": "حسين شحات", "id": "shahat"},
        {"name": "محمد العمري", "id": "omari"},
        {"name": "هاشم السقاف", "id": "saggaf"},
        {"name": "سهيل عبدالملك حافظ", "id": "hafez"},
        {"name": "عصام خان", "id": "khan"},
        {"name": "تركي الحسني", "id": "hasani"},
        {"name": "محمد با سعد", "id": "basaad"},
        {"name": "عبد الله باعفيف", "id": "baafif"},
        {"name": "إبراهيم مدني", "id": "madani"},
        {"name": "فاروق عبد الرحمن حضراوي", "id": "hadrawi"},
      ],
    },
    {
      "category": "مؤذنين كبار وقدامى",
      "muezzins": [
        {"name": "محمد رمل", "id": "raml"},
        {"name": "محمد يوسف مؤذن", "id": "yousef_moazen"},
        {"name": "محمد معروف", "id": "marouf"},
        {"name": "أحمد محمد مغربي", "id": "ahmed_maghribi"},
        {"name": "محمد مغربي", "id": "mohamed_maghribi"},
        {"name": "عبد الرحمن بن عبد الإله خاشقجي", "id": "khashoggi"},
        {"name": "عبد المطلب صالح أحمد نجدي", "id": "najdi"},
        {"name": "حسين عبدالله حسين رجب", "id": "rajab"},
        {"name": "حسين حمزة أمين عفيفي", "id": "afifi"},
        {"name": "حسن عبد الستار بخاري", "id": "h_bukhari"},
        {"name": "سامي محمد ديولي", "id": "diuli"},
        {"name": "عبد العزيز حسين بخاري", "id": "a_bukhari"},
        {"name": "عصام حسين بخاري", "id": "e_bukhari"},
        {"name": "ماجد حمزة حكيم", "id": "hakim"},
      ],
    },
    {
      "category": "مؤذني المدينة وجدة",
      "muezzins": [
        {"name": "محمد ماجد حمزه حكيم", "id": "m_hakim"},
        {"name": "كامل صالح أحمد نجدي", "id": "k_najdi"},
        {"name": "عمر يوسف محمد كمال", "id": "kamal"},
        {"name": "عبد الملك النعمان", "id": "a_numan"},
        {"name": "فيصل عبد الملك النعمان", "id": "f_numan"},
        {"name": "مصطفى عثمان نعمان", "id": "m_numan"},
        {"name": "سعود بن عبد العزيز بن حسين بخاري", "id": "s_bukhari"},
        {"name": "إياد بن أحمد بن عباس شكري", "id": "shukri"},
        {"name": "أشرف بن محمد بن حمزة عفيفي", "id": "a_afifi"},
        {"name": "عبد المجيد بن سلام بن عودة السريحي", "id": "surayhi"},
        {"name": "عمر بن نبيل بن حمزة سنبل", "id": "sunbul"},
        {"name": "محمد مروان قصاص", "id": "qassas"},
        {"name": "عادل عبدالرحمن كاتب", "id": "kateb"},
        {"name": "عبدالعزيز بن ماجد", "id": "bin_majid"},
      ],
    },
    {
      "category": "دولي ومنوع",
      "muezzins": [
        {"name": "أبو العينين شعيشع (مصر)", "id": "shaisha"},
        {"name": "أحمد خضر الطرابلسي (الكويت)", "id": "tarabulsi"},
        {"name": "أذان جامع الراجحي", "id": "rajhi"},
        {"name": "الشيخ علي البراق القيرواني (تونس)", "id": "barra_q"},
        {"name": "أذان كينيا", "id": "kenya"},
        {"name": "الدوكالي محمد العالم (ليبيا)", "id": "dukali"},
        {"name": "أنور دومان (تركيا)", "id": "duman"},
        {"name": "حسن خلفان (قطر)", "id": "khalfan"},
        {"name": "رابح بن دراح (الجزائر)", "id": "darrah"},
        {"name": "رعد الكردي", "id": "kurdi"},
        {"name": "سعد فريجة (لبنان)", "id": "freijah"},
        {"name": "سليم باهانان (إندونيسيا)", "id": "bahanan"},
        {"name": "عبد الرحمن الهندي", "id": "hindi"},
        {"name": "عبد الناصر حرك (الهند)", "id": "harak"},
      ],
    },
    {
      "category": "قراء ومشاهير",
      "muezzins": [
        {"name": "علي حسن عبد الخالق (قطر)", "id": "abdelkhaleq"},
        {"name": "محمد القلاجي", "id": "qallaji"},
        {"name": "محمد حمود (كولومبيا)", "id": "hamoud"},
        {"name": "محمد شقرون (تونس)", "id": "shaqrun"},
        {"name": "محمد صديق (أفغانستان)", "id": "siddiq"},
        {"name": "محمد صديق المنشاوي", "id": "minshawi"},
        {"name": "محمد صلاح الدين كبارة", "id": "kabbara"},
        {"name": "محمد عمر (باكستان)", "id": "omar"},
        {"name": "محمد ناصرالدين الألباني (الأردن)", "id": "albani"},
        {"name": "معاذ سيف الرحمن (باكستان)", "id": "saif_rahman"},
        {"name": "وديع حمادي (اليمن)", "id": "hammadi"},
        {"name": "ياسر الدوسري", "id": "dossari"},
        {"name": "ياسين العساف (العراق)", "id": "assaf"},
        {"name": "علي أحمد ملا (شيخ المؤذنين)", "id": "mulla"},
        {"name": "عبد الباسط عبد الصمد", "id": "abdulbasit"},
        {"name": "محمد رفعت", "id": "rifat"},
        {"name": "مصطفى اسماعيل", "id": "mustafa_ismail"},
        {"name": "محمود علي البنا", "id": "banna"},
        {"name": "نصر الدين طوبار", "id": "tobar"},
        {"name": "النقشبندي", "id": "naqshbandi"},
        {"name": "ناصر القطامي", "id": "qatami"},
        {"name": "أحمد النفيس", "id": "nafis"},
        {"name": "مشاري راشد العفاسي", "id": "mishary"},
      ],
    },
    {
      "category": "أذانات متنوعة (جديد)",
      "muezzins": [
        {"name": "أذان 1", "id": "adhan_1"},
        {"name": "أذان 2", "id": "adhan_2"},
        {"name": "أذان 3", "id": "adhan_3"},
        {"name": "أذان 4", "id": "adhan_4"},
        {"name": "أذان 5", "id": "adhan_5"},
        {"name": "أذان 6", "id": "adhan_6"},
        {"name": "أذان 7", "id": "adhan_7"},
        {"name": "أذان 8", "id": "adhan_8"},
        {"name": "أذان 9", "id": "adhan_9"},
        {"name": "أذان 10", "id": "adhan_10"},
        {"name": "أذان 11", "id": "adhan_11"},
        {"name": "أذان 12", "id": "adhan_12"},
        {"name": "أذان 13", "id": "adhan_13"},
        {"name": "أذان 14", "id": "adhan_14"},
        {"name": "أذان 15", "id": "adhan_15"},
        {"name": "أذان 16", "id": "adhan_16"},
        {"name": "أذان 17", "id": "adhan_17"},
        {"name": "أذان 18", "id": "adhan_18"},
        {"name": "أذان 19", "id": "adhan_19"},
        {"name": "أذان 20", "id": "adhan_20"},
        {"name": "أذان 21", "id": "adhan_21"},
        {"name": "أذان 22", "id": "adhan_22"},
        {"name": "أذان 23", "id": "adhan_23"},
        {"name": "أذان 24", "id": "adhan_24"},
        {"name": "أذان 25", "id": "adhan_25"},
        {"name": "أذان 26", "id": "adhan_26"},
        {"name": "أذان 27", "id": "adhan_27"},
        {"name": "أذان 28", "id": "adhan_28"},
        {"name": "أذان 29", "id": "adhan_29"},
        {"name": "أذان 30", "id": "adhan_30"},
        {"name": "أذان 31", "id": "adhan_31"},
        {"name": "أذان 32", "id": "adhan_32"},
        {"name": "أذان 33", "id": "adhan_33"},
        {"name": "أذان 34", "id": "adhan_34"},
        {"name": "أذان 35", "id": "adhan_35"},
        {"name": "أذان 36", "id": "adhan_36"},
        {"name": "أذان 37", "id": "adhan_37"},
      ],
    },
  ];
}
